### ISSUE TITLE
Suggest using linux Precision Time Protocol (PTP) for better sync in readme

### ISSUE THREAD

**Issue by kolorafa** [blaa/WaveSync#3] opened 2019-02-03 21:59 UTC
1ms delay between devices is still huge if the devices are close to each other, 
the best way to synchronize devices is to setup ntp server on one device and use ntpdate in loop to sync time, the overall efect is still "good enought", but it can be even better (or even perfect sync) with PTP

http://linuxptp.sourceforge.net/

https://jfearn.fedorapeople.org/fdocs/en-US/Fedora_Draft_Documentation/0.1/html/System_Administrators_Guide/sec-Starting_ptp4l.html

https://github.com/twteamware/raspberrypi-ptp

**Comment by blaa** [comment] 2019-02-04 17:03
I can relate docs to PTP.
There's a sensible limit of precision though: speed of sound in air is ~ 343m/s. So in 1ms sound travels 34cm - with 1ms difference you could reposition your head to get a perfect sync by moving it 17cm away from one device and closer to the other. 

I believe most audible differences are more into 20-40ms territory and are caused by variance in the output buffer. Differences in room-size-propagation-time are not worth chasing in practice. For a 5m room/corridor that would be around 14.6ms if I calculate correctly (distance = 343/1000 * t). It's good to think about it because it puts the synchronization in the context.

**Comment by kolorafa** [comment] 2019-02-05 07:51
True, i didn't look into speed of sound, but rather in my case somehow my device clock was very bad and setting up just ntpd to sync clock would not compensate for the drift, doing ntpdate in loop did look bad, while installing and just running linuxptp with one command was easy and it synced very nicely. But in the end i found that you can switch the clock source and it fixed the drift nicely, by ten I got to deep  into the "perfect sync", but in the end that difference should not be worth chasing. People learn whole life :)

So if someone also get a big drift in clock, they can try changing clock source:

`cat /sys/devices/system/clocksource/clocksource0/available_clocksource`
`cat /sys/devices/system/clocksource/clocksource0/current_clocksource`
eg. `echo hpet > /sys/devices/system/clocksource/clocksource0/current_clocksource`

**Comment by blaa** [comment] 2019-03-21 18:10
I added ptp to docs so I'll close this issue for now. I believe there are other, more important sources of synchronisations problems. ;) 2.0 needs tests.

**Closed as completed by blaa** 2019-03-21 18:10 UTC
